# Usa Node.js estável
FROM node:22

# Cria diretório de trabalho
WORKDIR /app

# Copia arquivos de dependências
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia o resto do projeto
COPY . .

# Expõe a porta do Render
EXPOSE 10000

# Inicia a aplicação
CMD ["npm", "start"]
